name: Deploy to Astronomer

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch


env:
   ASTRO_API_TOKEN:: ${{ secrets.ASTRONOMER_API_KEY }}
   DEPLOYMENT_ID: ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.8.0
